# NumPy

Why NumPy ?

NumPy is an acronym for "Numeric Python" or "Numerical Python"

[NumPy](http://www.numpy.org/) is the fundamental package for scientific computing with Python. It contains among other things:

* A powerful N-dimensional array object (ndarray) - efficiently implemented multi-dimensional arrays
* Array oriented computing - sophisticated (broadcasting) functions
* Tools for integrating C/C++ and Fortran code
* Designed for scientific computation - useful linear algebra, Fourier transform, and random number capabilities

In [39]:
# import NumPy library
# This library is bundled along with anaconda distribution
# np alias is the standard convention

import numpy as np

### numpy array (ndarray)

* A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers

* **ndarray.ndim** - the number of axes (dimensions) of the array. In the Python world, the number of dimensions is referred to as rank.

* **ndarray.shape** - the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension.

* **ndarray.size** - the total number of elements of the array. This is equal to the product of the elements of shape.

* **ndarray.dtype** - an object describing the type of the elements in the array.

<img src="fig_numpy_axes.png " alt="NumPy axes" height="300" width="300" align="left">

In [40]:
%%timeit
temp_list = range(100000)
temp_list1 = [ x*2 for x in temp_list]

100 loops, best of 3: 8.3 ms per loop


In [41]:
%%timeit
temp_array = np.arange(100000)
temp_array1 = temp_array*2

1000 loops, best of 3: 308 µs per loop


In [42]:
# ndarray can be created for regular python list or tupple
mylist = [2,5,8,15,25]
array = np.array(mylist)

In [43]:
type(array)

numpy.ndarray

In [44]:
array.shape

(5,)

In [45]:
array[0]

2

In [46]:
array[0:3]

array([2, 5, 8])

In [47]:
array.dtype

dtype('int64')

In [48]:
array.ndim

1

In [49]:
# dtype can be mentioned while creating an array
array2 = np.array(mylist,dtype=np.float)

In [50]:
array2

array([  2.,   5.,   8.,  15.,  25.])

In [51]:
array2.dtype

dtype('float64')

In [52]:
# creating a 5 X 3 multi dimensional array
marray = np.arange(15).reshape(5,3)

In [53]:
marray

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [54]:
marray.ndim

2

In [55]:
marray.shape

(5, 3)

In [56]:
marray.size

15

In [57]:
# ravel function generates a flattens 
marray.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [58]:
# reshape can be used to change the shape of an array
marray.ravel().reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [59]:
marray.shape

(5, 3)

### Array basic operations

In [60]:
# multiplying a scalr and ndarray
marray*2

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [61]:
marray

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [62]:
# inplace change
# there are certain operations that will modify the object inplace like one below
marray += 10

In [63]:
marray

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

In [64]:
# Guess - what would be the result of the following
marray > 15

array([[False, False, False],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

In [65]:
arr_A = np.array( [ [2,3], [4,5] ] )
arr_B = np.array( [ [1,1], [2,1] ] )

In [66]:
# * operates element wise
arr_A * arr_B

array([[2, 3],
       [8, 5]])

In [67]:
# dot is used for matrix multiplication
# np.dot(arr_A,arr_B) also works
arr_A.dot(arr_B)

array([[ 8,  5],
       [14,  9]])

### Array Slicing

In [68]:
marray[0]

array([10, 11, 12])

In [69]:
marray[0,1]

11

In [70]:
marray

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

In [71]:
marray[:,1:3]

array([[11, 12],
       [14, 15],
       [17, 18],
       [20, 21],
       [23, 24]])

In [72]:
marray[0:3,:]

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [73]:
marray[1:3,1:]`

SyntaxError: invalid syntax (<ipython-input-73-71883b19da69>, line 1)

### Broadcasting

* The term [Broadcasting](http://scipy.github.io/old-wiki/pages/EricsBroadcastingDoc) describes how numpy treats arrays with different shapes during arithmetic operations.
* Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes.
* Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python.

<img src="fig_broadcast_visual_1.png" alt="Broadcasting" height="500" width="500", align="left">

### Exercises

In [74]:
# Exercise - 1
# Construct  3 by 3 ndarray with 5 as diagonal elemet and 1 as remaining elements
# [[5, 1, 1][1,5,1][1,1,5]]
# Tip : explore np.ones and np.eye functions
# the dtype should be int

In [75]:
# Exercise
# try following array slicing
a = np.arange(0,60).reshape(6,10)[0:6,0:6]

In [76]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [77]:
np.eye(3,3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

<img src="fig_numpy_indexing_q.png " alt="Array Slicing" height="300" width="300" align="left">

In [78]:
np.ones((3,3))+np.eye(3,3)

array([[ 2.,  1.,  1.],
       [ 1.,  2.,  1.],
       [ 1.,  1.,  2.]])

In [79]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [80]:
array[3:5:]

array([15, 25])

In [23]:
a[0:1,3:5]

array([[3, 4]])

In [96]:
a[1:5:3,0:5:3]

array([[10, 13],
       [40, 43]])

### NumPy functions used for performing computations

* np.sum
* np.std
* np.mean
* np.max
* np.min

In [39]:
# np.NaN is a datatype - Not a Number
np.NaN?

In [42]:
d=np.array([None,1,2,3,None],dtype=np.float)

In [43]:
d.sum()

nan

In [35]:
np.random.seed(0)
arr_c = np.random.random(15).reshape((5,3))
arr_c

array([[ 0.5488135 ,  0.71518937,  0.60276338],
       [ 0.54488318,  0.4236548 ,  0.64589411],
       [ 0.43758721,  0.891773  ,  0.96366276],
       [ 0.38344152,  0.79172504,  0.52889492],
       [ 0.56804456,  0.92559664,  0.07103606]])

In [36]:
arr_c.sum()

9.0429600485654724

In [37]:
arr_c.min()

0.071036058197886942

In [38]:
arr_c.max()

0.96366276050102928

In [44]:
arr_c.mean(axis=0)

array([ 0.496554  ,  0.74958777,  0.56245025])

In [45]:
arr_c.mean(axis=1)

array([ 0.62225542,  0.53814403,  0.76434099,  0.56802049,  0.52155909])

In [48]:
arr_c.mean()

0.60286400323769818